apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    {{- include "books.labels" . | nindent 4}}
    app.kubernetes.io/component: books
spec:
  replicas: {{ .Values.books.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: books
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: books
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: books
          image: {{ .Values.books.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef: 
                  name: mongodb
                  key: books_db_url
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
