apiVersion: v1
kind: secret
metadata:
    name: mongodb
    labels:
        app.kubernetes.io/component: mongodb
        {{- include "books.labels" , | nindent 4 }}
type: Opaque
data:
    books_db_url: {{ .Values.booksMongoUrl | b64enc }}