apiVersion: v1
kind: Service
metadata: 
  name: books
  labels:
    {{- include "books.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec: 
  selector:
    app.kubernetes.io/name: books
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - targetPort: 3000
      protocol: TCP
      name: http
      port: 3000